---
title: "Age_menarche_groups"
author: "MEAB"
date: "23/08/2020"
output: html_document
---

```{r setup, include=FALSE}

packages <- c("lme4" , "ggplot2","tidyr","dplyr", "psych","ggcorrplot","mice","BaylorEdPsych","readxl","Amelia","MissMech","data.table")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)

cas_dir="Y:/dsnlab/TAG/"
set.seed(88)

######
# Run the Puberty_timing_all script until the imputation section to get the right data
######

age_menarche_gr <- read.csv(paste0(cas_dir,'projects/W1_W2_pubertal_timing/Age_menarche_dichotomized.csv'),header=T,sep=",")  %>% dplyr::select(tagid,menarche_pre11p73years)
all_pub_int <- merge(all_pub_int,age_menarche_gr,by="tagid",all=T)

```


```{r imputation}


#impute
#age is imputed to be 1.5 years after wave 1 if it's missing, then used as time variable in Amelia
age_imp <- pivot_wider(all_pub_int[,c("tagid","wave","age")],names_from="wave",values_from="age",names_prefix="age_wave")
age_imp <- age_imp %>%
  mutate(age_wave2=ifelse(is.na(age_wave2),age_wave1+1.5,age_wave2)) %>%
  pivot_longer(.,cols=contains("age"),names_to = c(".value","wave"), names_pattern = "(.*)_wave(.*)")

all_for_imp <- merge(age_imp,
                     subset(all_pub_int, select = -c(age,int_d,pdsstage,ldstage,ADRENcomp,GONADcomp,PUBcomp)),
                     by=c("tagid","wave"))
    
imp <- amelia(all_for_imp,m=25,p2s=0,idvars="wave",ts="age",cs="tagid",
             noms=c("menarche_pre11p73years","depres_d","anx_d","distress_d","fear_d"),
              ords=c("subj_timing","parent_subj_timing","adrenf2","gonadf2","PBIP_1A","PBIP_2A"),
              logs=c("CESDC_total"),priors = NULL, lags = NULL, empri = 0, intercs = FALSE, 
             leads = NULL, splinetime = NULL,bounds = NULL, max.resample = 1000, tolerance = 1e-04)

# check the performance of Amelia
for (vari in c("CESDC_total","SCARED_mean","CTQ_threat","DHEA_cor","TEST_cor","EST_cor",
               "subj_timing","parent_subj_timing","parent_pdsstage","adrenf2","gonadf2","PBIP_1A","PBIP_2A")) {
 overimputeplot <- overimpute(imp,var=vari)
 overimputeplot }

#average imputations
completedData <- do.call(rbind.data.frame, imp$imputations)
completedData <- setDT(completedData, keep.rownames = "imputation")[] 
completedData <- completedData %>% 
  mutate(imputation=gsub("\\..*","",imputation)) %>%
  select(tagid,imputation,wave,depres_d,anx_d,distress_d,fear_d,subj_timing,parent_subj_timing,adrenf2,gonadf2,PBIP_1A,PBIP_2A,everything()) 
agg <- aggregate(completedData[,14:21] , by = list(tagid=completedData$tagid,wave=completedData$wave),FUN= mean)
agg2 <- aggregate(completedData[,4:13] , by = list(tagid=completedData$tagid,wave=completedData$wave),FUN= median)
agg3 <- aggregate(completedData[,22] , by = list(tagid=completedData$tagid,wave=completedData$wave),FUN= median)
all_im <- agg %>% left_join(.,agg2) %>% left_join(.,agg3) %>% select(tagid, wave, everything()) %>% 
  rename(menarche_pre11p73years=x)

#recalculate ldstage, pdsstage, composites and int_d
all_im <- all_im %>%
  mutate(ldstage=rowMeans(select(.,PBIP_1A,PBIP_2A)),
         pdsstage=rowMeans(select(.,adrenf2,gonadf2)),
         ADRENcomp=rowMeans(select(.,adrenf2,PBIP_2A)),
         GONADcomp=rowMeans(select(.,gonadf2,PBIP_1A)),
         PUBcomp=rowMeans(select(.,gonadf2,PBIP_1A,adrenf2,PBIP_2A)),
         int_d=ifelse(depres_d==1|anx_d==1,1,0))


#put in short format
all_for_imp_short <- all_pub_int %>% pivot_wider(id_cols= tagid, names_from = wave, names_prefix = "wave", values_from = c(age,pdsstage,ldstage,parent_pdsstage,ADRENcomp,GONADcomp,PUBcomp,subj_timing,parent_subj_timing,DHEA_cor,TEST_cor,EST_cor,SCARED_mean,CESDC_total,depres_d,anx_d,int_d,distress_d,fear_d,CTQ_threat,menarche_pre11p73years)) 
all_im_short <- all_im %>% pivot_wider(id_cols= tagid, names_from = wave, names_prefix = "im_wave", values_from = c(age,pdsstage,ldstage,parent_pdsstage,ADRENcomp,GONADcomp,PUBcomp,subj_timing,parent_subj_timing,DHEA_cor,TEST_cor,EST_cor,SCARED_mean,CESDC_total,depres_d,anx_d,int_d,distress_d,fear_d,CTQ_threat,menarche_pre11p73years)) 

```

``` {r tests and plots}

#Test associations betwween binary age at menarche variable and MH variables
wilcox.test(CESDC_total_im_wave2 ~ menarche_pre11p73years_im_wave1, data=all_im_short)
wilcox.test(SCARED_mean_im_wave2 ~ menarche_pre11p73years_im_wave1, data=all_im_short)
chisq.test(all_im_short$int_d_im_wave2, all_im_short$menarche_pre11p73years_im_wave1)
chisq.test(all_im_short$depres_d_im_wave2, all_im_short$menarche_pre11p73years_im_wave1)
chisq.test(all_im_short$anx_d_im_wave2, all_im_short$menarche_pre11p73years_im_wave1)
chisq.test(all_im_short$distress_d_im_wave2, all_im_short$menarche_pre11p73years_im_wave1)
chisq.test(all_im_short$fear_d_im_wave2, all_im_short$menarche_pre11p73years_im_wave1)

#Plotting
ggplot(all_im_short,aes(x=as.factor(menarche_pre11p73years_im_wave1),y=CESDC_total_im_wave2)) + 
  geom_dotplot(binaxis = "y", stackdir = "center",binwidth=0.01) + 
  geom_violin(fill="none") +
  theme_minimal()+ 
  labs(x="0=Average or later menarche,1=Early menarche", y="Depressive symptoms")
ggplot(all_im_short,aes(x=as.factor(menarche_pre11p73years_im_wave1),y=SCARED_mean_im_wave2)) + 
  geom_dotplot(binaxis = "y", stackdir = "center",binwidth=0.01) + 
  geom_violin(fill="none") +
  theme_minimal()+ 
  labs(x="0=Average or later menarche,1=Early menarche", y="Anxiety symptoms")
ggplot(all_im_short,aes(x=as.factor(menarche_pre11p73years_im_wave1),y=as.factor(distress_d_im_wave2))) + 
  geom_jitter()+ theme_minimal()+
  labs(x="0=Average or later menarche,1=Early menarche", y="Distress disorder")

```

