---
title: "Pubertaltiming_alltheways"
output: html_document
---

```{r setup, include=FALSE}
packages <- c("lme4" , "ggplot2","tidyr","dplyr", "psych","ggcorrplot","mice","BaylorEdPsych","readxl","Amelia","MissMech","data.table")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)

cas_dir="Y:/dsnlab/TAG/"
set.seed(88)
```

```{r Combine all puberty measures in long format, include=FALSE}

#PDS, LD, and composite measures
PubertyComposite <- read.table(paste0(cas_dir,'behavior/Questionnaires/Puberty/Allwaves_PubertyComposite.csv'),header=T,sep=",") %>%
  filter(wave<3) %>% select(-age) %>%
  dplyr::rename(pdsstage=pdss, ldstage=stage)

#replace age with most complete data
Age <- read.csv(paste0(cas_dir,'behavior/Demographics/Age/TAG_age.csv'),header=T,sep=",") %>% 
        filter(wave<3) %>% filter(session==2) %>% 
        select(tagid,wave,age_excel) %>%
        dplyr::rename(age=age_excel)
# Two people had a session 1 at T2, but no session 2. We manually impute age here for these two people before any analyses are done (T2 age = age at session 1 + 1 month, instead of less accurate age imputation of Wave 1 + 18 months, which is done later for everyone missing entire Wave 2)
Age[264,3] = 13.40274 + 0.08333
Age[283,3] = 12.13425 + 0.08333

#Get PDS_F5(subjective timing) all waves 
ChildPDS_wave1 <- read.csv(paste0(cas_dir,'behavior/Questionnaires/Wave1/PDS_Wave1.csv')) %>%
  select(tagid, PDS_F1, PDS_F2, PDS_F3, PDS_F4, PDS_F5, PDS_F6, pdss) %>%
  mutate(wave = 1) %>%
  dplyr::rename(subj_timing=PDS_F5,pdsstage=pdss)
ChildPDS_wave2 <- read.csv(paste0(cas_dir,'behavior/Questionnaires/Wave2/PDS_Wave2.csv')) %>%
  select(tagid, PDS_F1, PDS_F2, PDS_F3, PDS_F4, PDS_F5, PDS_F6, pdss) %>%
  mutate(wave = 2) %>%
  dplyr::rename(subj_timing=PDS_F5,pdsstage=pdss)
ChildPDS <- rbind(ChildPDS_wave1,ChildPDS_wave2)

#Get parent pds 
#Note that Parent PDS is missing for half of pp at wave 1
ParentPDS_wave1 <- read.csv(paste0(cas_dir,'behavior/Questionnaires/Wave1/PDS_parent_Wave1.csv')) %>%
  select(tagid, PDS_F1, PDS_F2, PDS_F3, PDS_F4, PDS_F5, PDS_F6, pdss) %>%
  mutate(wave = 1) %>%
  dplyr::rename(parent_subj_timing=PDS_F5,parent_pdsstage=pdss)
ParentPDS_wave2 <- read.csv(paste0(cas_dir,'behavior/Questionnaires/Wave2/PDS_parent_Wave2.csv')) %>%
  select(tagid, PDS_F1, PDS_F2, PDS_F3, PDS_F4, PDS_F5, PDS_F6, pdss) %>%
  mutate(wave = 2) %>%
  dplyr::rename(parent_subj_timing=PDS_F5,parent_pdsstage=pdss)
ParentPDS <- rbind(ParentPDS_wave1,ParentPDS_wave2)

#merge all the measures in one dataframe
Puberty_all <- merge(PubertyComposite[,c("tagid","wave","adrenf2","gonadf2","PBIP_1A","PBIP_2A","ldstage","ADRENcomp","GONADcomp","PUBcomp")], ChildPDS[,c("tagid","wave","pdsstage","subj_timing")], by=c("tagid","wave"),all=T)
Puberty_all <- merge(Puberty_all, ParentPDS[,c("tagid","wave", "parent_pdsstage","parent_subj_timing")], by=c("tagid","wave"),all=T)
Puberty_all <- merge(Puberty_all, Age, by=c("tagid","wave"),all=T)

#Only wave 1 and 2
Puberty_allways <- Puberty_all %>% filter(wave<3)

#Add hormones
Hormones <- read.table(paste0(cas_dir,'behavior/Puberty/Saliva//TAG_W1W2_Saliva_basalestimates.csv'), header=T, sep=",") %>% 
  select(SID,DHEAcoef_imp_wave1,TESTcoef_imp_wave1,ESTcoef_imp_wave1,DHEAcoef_imp_wave2,TESTcoef_imp_wave2,ESTcoef_imp_wave2) %>%
  mutate(tagid=sprintf("TAG%03d", SID)) %>% select(-SID) %>%
  pivot_longer(cols=contains("wave"),names_to = c(".value","wave"), names_pattern = "(.*)_wave(.*)") %>%
  rename(DHEA_cor=DHEAcoef_imp,TEST_cor=TESTcoef_imp,EST_cor=ESTcoef_imp)

Puberty_allways <- merge(Puberty_allways,Hormones,by=c("tagid","wave"),all=T)

#Filter out excluded participants
overview <- read_excel(paste0(cas_dir,'behavior/Overview/Overview_Withdrawn_Completed/TAG_Overview_Doc.xlsx'),sheet=1)
overview <- overview[,c("TAG_ID","W1S2_Completed","Withdrawn_W1","Exclusionary_Withdrawl")]
overview <- overview %>% 
  rename(tagid = TAG_ID) %>%
  replace_na(list(Withdrawn_W1 = 0)) %>%
  replace_na(list(Exclusionary_Withdrawl = 0)) %>% 
  arrange(Exclusionary_Withdrawl) %>% 
  filter(Exclusionary_Withdrawl==0) %>%
  filter(Withdrawn_W1==0)
Puberty_allways <- Puberty_allways %>% filter(tagid %in% overview$tagid)

```

```{r checks on parent pds}

# First check missing data percentages and mechanism:
Missinginfo_pub <- OrderMissing(Puberty_allways, del.lesscases = 0)
Missinginfo_pub_W1 <- OrderMissing(Puberty_allways[which(Puberty_allways$wave=='1'), ], del.lesscases = 0)
Missinginfo_pub_W2 <- OrderMissing(Puberty_allways[which(Puberty_allways$wave=='2'), ], del.lesscases = 0)
summary(Missinginfo_pub)
summary(Missinginfo_pub_W1)
summary(Missinginfo_pub_W2)

#data.nummat <- data.matrix(Puberty_allways, rownames.force = NA)
#data.out <- TestMCARNormality(data.nummat) # tests (parametric and nonparametric) for MCAR. But John said no, MCAR testing is not useful :)
#print(data.out)

# Next, for the W1 parent_PDSstage, which is the only variable assumed missing not at random (because we introduced it at W1 halfway through, and we recruited older girls first), check if any observed vars at W1 are associated with whether or not they were given the parent PDS (0 = not given, 1 = given).
have_parPDS <- read.csv(file.path(cas_dir,"projects/W1_W2_pubertal_timing/before_after_parentPDSw1.csv", fsep=""))
parPDScompare <- merge(Puberty_allways, have_parPDS, by = c("tagid", "wave"), all=T)
w1_parPDScompare <- parPDScompare[which(parPDScompare$wave=='1'),]

# Compare each stage variable. I've marked stats if significantly different.
age_parPDScompare <- t.test(w1_parPDScompare$age ~ w1_parPDScompare$before_after_parentPDSw1) #t = 4.278, df = 153.25, p-value = 3.306e-05, mean in group 0 = 11.85999, mean in group 1 = 11.34985
pdsstage_parPDScompare <- t.test(w1_parPDScompare$pdsstage ~ w1_parPDScompare$before_after_parentPDSw1)

ldstage_parPDScompare <- t.test(w1_parPDScompare$ldstage ~ w1_parPDScompare$before_after_parentPDSw1) # t = 3.3172, df = 152.36, p-value = 0.001137, mean in group 0 = 3.056962, mean in group 1 = 2.585526

ADRENcomp_parPDScompare <- t.test(w1_parPDScompare$ADRENcomp ~ w1_parPDScompare$before_after_parentPDSw1) # t = 2.169, df = 162.62, p-value = 0.03153, mean in group 0 = 3.033708, mean in group 1 = 2.675325

GONADcomp_parPDScompare <- t.test(w1_parPDScompare$GONADcomp ~ w1_parPDScompare$before_after_parentPDSw1) # t = 3.1529, df = 161.78, p-value = 0.001927, mean in group 0 = 3.155172, mean in group 1 = 2.724359

PUBcomp_parPDScompare <- t.test(w1_parPDScompare$PUBcomp ~ w1_parPDScompare$before_after_parentPDSw1) # t = 2.8976, df = 161.54, p-value = 0.004283, mean in group 0 = 3.089080, mean in group 1 = 2.694805

subj_timing_parPDScompare <- t.test(w1_parPDScompare$subj_timing ~ w1_parPDScompare$before_after_parentPDSw1)

DHEA_cor_parPDScompare <- t.test(w1_parPDScompare$DHEA_cor ~ w1_parPDScompare$before_after_parentPDSw1) # t = 2.1072, df = 164.35, p-value = 0.03662, mean in group 0 = 4.329900, mean in group 1 = 4.035578

TEST_cor_parPDScompare <- t.test(w1_parPDScompare$TEST_cor ~ w1_parPDScompare$before_after_parentPDSw1) # t = 2.7963, df = 161.9, p-value = 0.005796, mean in group 0 = 3.769135, mean in group 1 = 3.614615

EST_cor_parPDScompare <- t.test(w1_parPDScompare$EST_cor ~ w1_parPDScompare$before_after_parentPDSw1) # t = 3.9926, df = 162.86, p-value = 9.868e-05, mean in group 0 = 1.604741, mean in group 1 = 1.559396

```

```{r combine puberty variables with mh variables and covariates}

#remove duplicates (TAG077 and TAG124 wave 2) # Don't seem to be in later versions of data so commented out
#Puberty_allways <- Puberty_allways[!duplicated(Puberty_allways[c("tagid","wave")]),]

#load mh variables
Internalizing_all <- read.csv(paste0(cas_dir,"projects/W1_W2_pubertal_timing/Internalizing_allways.csv"),header=T,sep=",")
Internalizing_all_long <- pivot_longer(Internalizing_all,cols=contains("w"),names_to = c(".value","wave"), names_pattern = "(.*)_w(.*)")
#merge
all_pub_int <- merge(Puberty_allways,Internalizing_all_long,by=c("tagid","wave"))
#covariates
CTQ <- read.csv(paste0(cas_dir,"projects/W1_W2_pubertal_timing/W1_CTQ_threatscoring.csv")) 
CTQ <- CTQ %>% 
  rename(CTQ_threat=CTQ_threat_total_75perc) %>% 
  mutate(tagid=sprintf("TAG%03d", SID))
all_pub_int <- all_pub_int %>%
  merge(.,CTQ[,c("tagid","CTQ_threat")],by=c("tagid"),all.x=T)
#  merge(.,have_parPDS,by=c("tagid","wave")) 
                              
Missinginfo_pubmh <- OrderMissing(all_pub_int, del.lesscases = 0)
Missinginfo_pubmh_W1 <- OrderMissing(all_pub_int[which(all_pub_int$wave=='1'), ], del.lesscases = 0)
Missinginfo_pubmh_W2 <- OrderMissing(all_pub_int[which(all_pub_int$wave=='2'), ], del.lesscases = 0)
summary(Missinginfo_pubmh)
summary(Missinginfo_pubmh_W1)
summary(Missinginfo_pubmh_W2)
```

```{r imputation}

#Note: we're not imputing age at menarche (added below) because missings are mostly pre-menarcheal girls (=MNAR)

#check missingness pattern
md.pattern(all_pub_int)

#impute
#age is imputed to be 1.5 years after wave 1 if it's missing, then used as time variable in Amelia
age_imp <- pivot_wider(all_pub_int[,c("tagid","wave","age")],names_from="wave",values_from="age",names_prefix="age_wave")
age_imp <- age_imp %>%
  mutate(age_wave2=ifelse(is.na(age_wave2),age_wave1+1.5,age_wave2)) %>%
  pivot_longer(.,cols=contains("age"),names_to = c(".value","wave"), names_pattern = "(.*)_wave(.*)")

all_for_imp <- merge(age_imp,
                     subset(all_pub_int, select = -c(age,int_d,pdsstage,ldstage,ADRENcomp,GONADcomp,PUBcomp)),
                     by=c("tagid","wave"))
    
imp <- amelia(all_for_imp,m=25,p2s=0,idvars="wave",ts="age",cs="tagid",
             noms=c("depres_d","anx_d","distress_d","fear_d"),
              ords=c("subj_timing","parent_subj_timing","adrenf2","gonadf2","PBIP_1A","PBIP_2A"),
              logs=c("CESDC_total"),priors = NULL, lags = NULL, empri = 0, intercs = FALSE, 
             leads = NULL, splinetime = NULL,bounds = NULL, max.resample = 1000, tolerance = 1e-04)

# check the performance of Amelia
#The imputation does a bad job for CTQ_threat, the rest looks ok
for (vari in c("CESDC_total","SCARED_mean","CTQ_threat","DHEA_cor","TEST_cor","EST_cor")) {
 densityplot <- compare.density(imp,vari)
 densityplot }
for (vari in c("CESDC_total","SCARED_mean","CTQ_threat","DHEA_cor","TEST_cor","EST_cor",
               "subj_timing","parent_subj_timing","parent_pdsstage","adrenf2","gonadf2","PBIP_1A","PBIP_2A")) {
 overimputeplot <- overimpute(imp,var=vari)
 overimputeplot }

#average imputations
completedData <- do.call(rbind.data.frame, imp$imputations)
completedData <- setDT(completedData, keep.rownames = "imputation")[] 
completedData <- completedData %>% 
  mutate(imputation=gsub("\\..*","",imputation)) %>%
  select(tagid,imputation,wave,depres_d,anx_d,distress_d,fear_d,subj_timing,parent_subj_timing,adrenf2,gonadf2,PBIP_1A,PBIP_2A,everything()) 
agg <- aggregate(completedData[,14:21] , by = list(tagid=completedData$tagid,wave=completedData$wave),FUN= mean)
agg2 <- aggregate(completedData[,4:13] , by = list(tagid=completedData$tagid,wave=completedData$wave),FUN= median)
all_im <- agg %>% left_join(.,agg2) %>% select(tagid, wave, everything())

#recalculate ldstage, pdsstage, composites and int_d
all_im <- all_im %>%
  mutate(ldstage=rowMeans(select(.,PBIP_1A,PBIP_2A)),
         pdsstage=rowMeans(select(.,adrenf2,gonadf2)),
         ADRENcomp=rowMeans(select(.,adrenf2,PBIP_2A)),
         GONADcomp=rowMeans(select(.,gonadf2,PBIP_1A)),
         PUBcomp=rowMeans(select(.,gonadf2,PBIP_1A,adrenf2,PBIP_2A)),
         int_d=ifelse(depres_d==1|anx_d==1,1,0))

#check distribution imputed variables
#put in short format
  # non-imputed data:
all_for_imp_short <- all_pub_int %>% pivot_wider(id_cols= tagid, names_from = wave, names_prefix = "wave", values_from = c(age,pdsstage,ldstage,parent_pdsstage,ADRENcomp,GONADcomp,PUBcomp,subj_timing,parent_subj_timing,DHEA_cor,TEST_cor,EST_cor,SCARED_mean,CESDC_total,depres_d,anx_d,int_d,distress_d,fear_d,CTQ_threat)) 
  # imputed data:
all_im_short <- all_im %>% pivot_wider(id_cols= tagid, names_from = wave, names_prefix = "im_wave", values_from = c(age,pdsstage,ldstage,parent_pdsstage,ADRENcomp,GONADcomp,PUBcomp,subj_timing,parent_subj_timing,DHEA_cor,TEST_cor,EST_cor,SCARED_mean,CESDC_total,depres_d,anx_d,int_d,distress_d,fear_d,CTQ_threat)) 

#plot
all_for_imp_short %>% 
  select(-tagid,-depres_d_wave1,-anx_d_wave1,-int_d_wave1,-distress_d_wave1,-fear_d_wave1,-depres_d_wave2,-anx_d_wave2,-int_d_wave2,-distress_d_wave2,-fear_d_wave2) %>% gather() %>%
  ggplot(aes(value)) + facet_wrap(~ key, scales = "free") + geom_histogram()
all_im_short %>% 
  select(-tagid,-depres_d_im_wave1,-anx_d_im_wave1,-int_d_im_wave1,-distress_d_im_wave1,-fear_d_im_wave1,-depres_d_im_wave2,-anx_d_im_wave2,-int_d_im_wave2,-distress_d_im_wave2,-fear_d_im_wave2) %>% gather() %>%
  ggplot(aes(value)) + facet_wrap(~ key, scales = "free") + geom_histogram()

```


Pubertal timing
```{r Pubertal timing from residuals}
#set up timing dataframe
Timing_allways <- merge(all_im_short,all_for_imp_short,by="tagid")

#create residuals for each wave separately BEFORE IMPUTATION
pubcolumns1 <- list("ldstage_wave1","pdsstage_wave1","ADRENcomp_wave1","GONADcomp_wave1","PUBcomp_wave1","parent_pdsstage_wave1","DHEA_cor_wave1","TEST_cor_wave1","EST_cor_wave1")
for(Pub in pubcolumns1){
  modelap1 <- lm(formula = paste(Pub, "~ age_wave1"),data=all_for_imp_short,na.action=na.exclude)
  summary(modelap1)
  Timing_allways[[paste('resid',Pub, sep="_")]] <- resid(modelap1)
}

pubcolumns2 <- c("ldstage_wave2","pdsstage_wave2","ADRENcomp_wave2","GONADcomp_wave2","PUBcomp_wave2","parent_pdsstage_wave2","DHEA_cor_wave2","TEST_cor_wave2","EST_cor_wave2")
for(Pub in pubcolumns2){
  modelap2 <- lm(formula = paste(Pub, "~ age_wave2"),data=all_for_imp_short,na.action=na.exclude)
  summary(modelap2)
  Timing_allways[[paste('resid',Pub, sep="_")]] <- resid(modelap2)
}

#create residuals for each wave separately AFTER IMPUTATION
pubcolumns1a <- list("ldstage_im_wave1","pdsstage_im_wave1","ADRENcomp_im_wave1","GONADcomp_im_wave1","PUBcomp_im_wave1","parent_pdsstage_im_wave1","DHEA_cor_im_wave1","TEST_cor_im_wave1","EST_cor_im_wave1")
for(Pub in pubcolumns1a){
  modelap1a <- lm(formula = paste(Pub, "~ age_im_wave1"),data=Timing_allways,na.action=na.exclude)
  summary(modelap1a)
  Timing_allways[[paste('resid',Pub, sep="_")]] <- resid(modelap1a)
}

pubcolumns2a <- c("ldstage_im_wave2","pdsstage_im_wave2","ADRENcomp_im_wave2","GONADcomp_im_wave2","PUBcomp_im_wave2","parent_pdsstage_im_wave2","DHEA_cor_im_wave2","TEST_cor_im_wave2","EST_cor_im_wave2")
for(Pub in pubcolumns2a){
  modelap2a <- lm(formula = paste(Pub, "~ age_im_wave2"),data=Timing_allways,na.action=na.exclude)
  summary(modelap2a)
  Timing_allways[[paste('resid',Pub, sep="_")]] <- resid(modelap2a)
}

#regression with long format data and create residuals 
#pubcolumns <- c("ldstage","pdsstage","ADRENcomp","GONADcomp","PUBcomp","parent_pdsstage","DHEAmean","TESTmean","ESTmean","DHEA_cor","TEST_cor","EST_cor")
#for(Pub in pubcolumns){
#  modelap1 <- lmer(formula = paste(Pub, "~ age + ( 1 | tagid)"),data=Puberty_allways,na.action=na.exclude)
#  summary(modelap1)
#  Puberty_allways[[paste('resid',Pub, sep="_")]] <- resid(modelap1)
#}


```  

```{r add Age at menarche}

age_at_menarche <- read.csv(paste0(cas_dir,'behavior/Questionnaires/Puberty/Age_at_menarche_short_finalizing.csv'),header=T,sep=",") %>%
  dplyr::select(tagid,aam_final)
Timing_allways <- merge(Timing_allways,age_at_menarche,by="tagid",all=T)


#Adding hormone based timing variables based on the script "Basalestimates_W1W2"
#Hormone_timing <- read.table(paste0(cas_dir,'projects/W1_W2_pubertal_timing/TAG_W1W2_hormonebasedtiming.csv'), header=T, sep=",") %>% 
#  select(SID,DHEAcoef_imp_wave1,TESTcoef_imp_wave1,ESTcoef_imp_wave1,DHEAcoef_imp_wave2,TESTcoef_imp_wave2,ESTcoef_imp_wave2) %>%
#  mutate(tagid=sprintf("TAG%03d", SID))
#Hormone_timing <- Hormone_timing %>% pivot_longer(cols=contains("wave"),names_to = c(".value","wave"), names_pattern = "(.*)_wave(.*)") %>%
#  rename(DHEA_cor_interc=DHEAcoef_imp,TEST_cor_interc=TESTcoef_imp,EST_cor_interc=ESTcoef_imp) %>%
#  select(-SID)
#Timing_allways <- merge(Timing_allways,Hormone_timing,by=c("tagid","wave"),all=T)

```



```{r save}

# This ("Timing_and_internalizing.csv") is the final file with all data (imputed and non-imputed), and the residuals are original, meaning that for residuals on age, higher values are earlier timing (more advanced compared to peers) and lower values are later timing (less advanced). This is in contrast to the timing variables "subj_timing", "parent_subj_timing", and "aam_final" where lower values indicate earlier timing:
write.csv(Timing_allways,paste0(cas_dir,'projects/W1_W2_pubertal_timing/Timing_and_internalizing.csv'),row.names=F)

# But, in further analyses (like the SCA), we want all timing variables to go in the same direction (and we can't reverse code age at menarche), so here we will multiply the residuals only by -1. This way, all timing variables will be coded so that higher values are later timing (less advanced compared to peers), and lower values are earlier timing (more advanced compared to peers)
Timing_neg1_resid <- Timing_allways
resid_vars <- c("resid_ldstage_wave1", "resid_pdsstage_wave1", "resid_ADRENcomp_wave1", "resid_GONADcomp_wave1", "resid_PUBcomp_wave1", "resid_parent_pdsstage_wave1", "resid_DHEA_cor_wave1", "resid_TEST_cor_wave1", "resid_EST_cor_wave1", "resid_ldstage_wave2", "resid_pdsstage_wave2", "resid_ADRENcomp_wave2", "resid_GONADcomp_wave2", "resid_PUBcomp_wave2", "resid_parent_pdsstage_wave2", "resid_DHEA_cor_wave2", "resid_TEST_cor_wave2", "resid_EST_cor_wave2","resid_ldstage_im_wave1", "resid_pdsstage_im_wave1", "resid_ADRENcomp_im_wave1", "resid_GONADcomp_im_wave1", "resid_PUBcomp_im_wave1", "resid_parent_pdsstage_im_wave1", "resid_DHEA_cor_im_wave1", "resid_TEST_cor_im_wave1", "resid_EST_cor_im_wave1", "resid_ldstage_im_wave2", "resid_pdsstage_im_wave2", "resid_ADRENcomp_im_wave2", "resid_GONADcomp_im_wave2", "resid_PUBcomp_im_wave2", "resid_parent_pdsstage_im_wave2", "resid_DHEA_cor_im_wave2", "resid_TEST_cor_im_wave2", "resid_EST_cor_im_wave2")
resid_neg_vars <- c("resid_neg_ldstage_wave1", "resid_neg_pdsstage_wave1", "resid_neg_ADRENcomp_wave1", "resid_neg_GONADcomp_wave1", "resid_neg_PUBcomp_wave1", "resid_neg_parent_pdsstage_wave1", "resid_neg_DHEA_cor_wave1", "resid_neg_TEST_cor_wave1", "resid_neg_EST_cor_wave1", "resid_neg_ldstage_wave2", "resid_neg_pdsstage_wave2", "resid_neg_ADRENcomp_wave2", "resid_neg_GONADcomp_wave2", "resid_neg_PUBcomp_wave2", "resid_neg_parent_pdsstage_wave2", "resid_neg_DHEA_cor_wave2", "resid_neg_TEST_cor_wave2", "resid_neg_EST_cor_wave2","resid_neg_ldstage_im_wave1", "resid_neg_pdsstage_im_wave1", "resid_neg_ADRENcomp_im_wave1", "resid_neg_GONADcomp_im_wave1", "resid_neg_PUBcomp_im_wave1", "resid_neg_parent_pdsstage_im_wave1", "resid_neg_DHEA_cor_im_wave1", "resid_neg_TEST_cor_im_wave1", "resid_neg_EST_cor_im_wave1", "resid_neg_ldstage_im_wave2", "resid_neg_pdsstage_im_wave2", "resid_neg_ADRENcomp_im_wave2", "resid_neg_GONADcomp_im_wave2", "resid_neg_PUBcomp_im_wave2", "resid_neg_parent_pdsstage_im_wave2", "resid_neg_DHEA_cor_im_wave2", "resid_neg_TEST_cor_im_wave2", "resid_neg_EST_cor_im_wave2")
Timing_neg1_resid[resid_neg_vars] <- Timing_neg1_resid[resid_vars]*-1

write.csv(Timing_neg1_resid,paste0(cas_dir,'projects/W1_W2_pubertal_timing/Final_timing_int.csv'),row.names=F)


# NOTE: Run the dynamic timing window script after this - it calculates timing based on stage of windows of 6 month age peers (and also school grade peers) per person. It calls on the "Timing_and_internalizing.csv" which is all data, imputed and nonimputed, and where the residuals are original (i.e., not multiplied by -1) (the first outputted dataset)
```

```{r reorder and correlate all measures}

#Wave 1
Timing_allways1 <- Timing_neg1_resid %>% select(resid_neg_pdsstage_wave1,resid_neg_parent_pdsstage_wave1,resid_neg_ldstage_wave1,resid_neg_PUBcomp_wave1,resid_neg_ADRENcomp_wave1,resid_neg_GONADcomp_wave1,subj_timing_wave1,parent_subj_timing_wave1,resid_neg_DHEA_cor_wave1,resid_neg_TEST_cor_wave1,resid_neg_EST_cor_wave1,aam_final)

Timing_allways1 <- select_if(Timing_allways1, is.numeric) 
cor_timing1_r <- cor(Timing_allways1, use="pairwise.complete.obs", method="spearman")
colnames(cor_timing1_r) <- c("Residualized self-report PDS stage", "Residualized parent-report PDS stage", "Residualized LD stage", "Residualized puberty composite", "Residualized adrenal composite", "Residualized gonadal composite", "Self-report subjective timing", "Parent-report Subjective timing", "Residualized DHEA", "Residualized testosterone", "Residualized estradiol", "Age at menarche")
rownames(cor_timing1_r) <- colnames(cor_timing1_r)
p_timing1_r <- cor_pmat(Timing_allways1)
colnames(p_timing1_r) <- colnames(cor_timing1_r) 
rownames(p_timing1_r) <- rownames(cor_timing1_r) 
w1corrplot <- ggcorrplot(cor_timing1_r, lab=T,lab_size=4,type="lower",title="Pubertal timing correlations Time 1",colors = c("#e41a1c", "white", "#6897bb"))

#Wave 2
Timing_allways2 <- Timing_neg1_resid %>% select(resid_neg_pdsstage_wave2,resid_neg_parent_pdsstage_wave2,resid_neg_ldstage_wave2,resid_neg_PUBcomp_wave2,resid_neg_ADRENcomp_wave2,resid_neg_GONADcomp_wave2,subj_timing_wave2,parent_subj_timing_wave2,resid_neg_DHEA_cor_wave2,resid_neg_TEST_cor_wave2,resid_neg_EST_cor_wave2,aam_final)

Timing_allways2 <- select_if(Timing_allways2, is.numeric) 
cor_timing2_r <- cor(Timing_allways2, use="pairwise.complete.obs", method="spearman")
colnames(cor_timing2_r) <- colnames(cor_timing1_r)
rownames(cor_timing2_r) <- rownames(cor_timing1_r)
p_timing2 <- cor_pmat(Timing_allways2)
colnames(p_timing2) <- colnames(cor_timing1_r)
rownames(p_timing2) <- rownames(cor_timing1_r)
w2corrplot <- ggcorrplot(cor_timing2_r, lab=T, lab_size=4,type="lower", title="Pubertal timing correlations Time 2",colors = c("#e41a1c", "white", "#6897bb"))

#Both waves and all pubertal dev variables
Timing_allwaysn <- Timing_neg1_resid %>% select(resid_neg_pdsstage_wave1,resid_neg_parent_pdsstage_wave1,resid_neg_ldstage_wave1,resid_neg_PUBcomp_wave1,resid_neg_ADRENcomp_wave1,resid_neg_GONADcomp_wave1,subj_timing_wave1,parent_subj_timing_wave1,resid_neg_DHEA_cor_wave1,resid_neg_TEST_cor_wave1,resid_neg_EST_cor_wave1,resid_neg_pdsstage_wave2,resid_neg_parent_pdsstage_wave2,resid_neg_ldstage_wave2,resid_neg_PUBcomp_wave2,resid_neg_ADRENcomp_wave2,resid_neg_GONADcomp_wave2,subj_timing_wave2,parent_subj_timing_wave2,resid_neg_DHEA_cor_wave2,resid_neg_TEST_cor_wave2,resid_neg_EST_cor_wave2,aam_final)

cor_timing <- cor(Timing_allwaysn, use="pairwise.complete.obs", method="spearman")
p_timing <- cor_pmat(Timing_allwaysn)
ggcorrplot(cor_timing, p.mat=p_timing, lab=T,lab_size=4,type="lower", title="Pubertal timing correlations both waves",colors = c("#e41a1c", "white", "#6897bb"))


```

```{r try exp AAM}
# Just try a little non linear action between AAM and internalizing psychopathology for funsies
AAM_nl_tests <- Timing_neg1_resid
c = 1
# first visualize just W2 symptoms
aam_CESD_scatter <- ggplot(AAM_nl_tests, aes (x = aam_final, y = CESDC_total_im_wave2)) +
  geom_point(size = 3.5) +
  geom_smooth(method="lm", formula = (y ~ exp(x)), se = TRUE) +
  theme_bw()

aam_SCARED_scatter <- ggplot(AAM_nl_tests, aes (x = aam_final, y = SCARED_mean_im_wave2)) +
  geom_point(size = 3.5) +
  geom_smooth(method="lm", formula = (y ~ exp(x)), se = TRUE) +  
  theme_bw()

# Then visualize increase in symptoms from W1 to W2 (simple subtraction)
  
AAM_nl_tests$CESD_delta <- AAM_nl_tests$CESDC_total_im_wave2 - AAM_nl_tests$CESDC_total_im_wave1
AAM_nl_tests$SCARED_delta <- AAM_nl_tests$SCARED_mean_im_wave2 - AAM_nl_tests$SCARED_mean_im_wave1

aam_CESD_del_scatter <- ggplot(AAM_nl_tests, aes (x = aam_final, y = CESD_delta)) +
  geom_point(size = 3.5) +
  geom_smooth(method="lm", formula = (y ~ exp(x)), se = TRUE) +
  theme_bw()

aam_SCARED_del_scatter <- ggplot(AAM_nl_tests, aes (x = aam_final, y = SCARED_delta)) +
  geom_point(size = 3.5) +
  geom_smooth(method="lm", formula = (y ~ exp(x)), se = TRUE) +
  theme_bw()

# Look at linear and exp models with covariates
linear_aam_cesd <- summary(lm(CESDC_total_im_wave2 ~ aam_final + CESDC_total_im_wave1 + CTQ_threat_im_wave2, AAM_nl_tests))
exp_aam_cesd <- summary(lm(log(CESDC_total_im_wave2 + c) ~ aam_final + CESDC_total_im_wave1 + CTQ_threat_im_wave2, AAM_nl_tests))

linear_aam_scared <- summary(lm(SCARED_mean_im_wave2 ~ aam_final + SCARED_mean_im_wave1 + CTQ_threat_im_wave2, AAM_nl_tests))
exp_aam_scared <- summary(lm(log(SCARED_mean_im_wave2 + c) ~ aam_final + SCARED_mean_im_wave1 + CTQ_threat_im_wave2, AAM_nl_tests))
```

